St-14: Add all entities according to ERD
tareq-mahmood-sazim/superteacher-backend pull request #17
Opened 2024-10-08 08:56 UTC by tareq-mahmood-sazim

## Description of Change

- Removed previous changes as ERD has changed
- Created entities following new ERD
- Slight changes over controllers to match ERD
- Removed dependabot

## Please list which modules are affected by your changes

common/entities/**.ts, users/**.ts

---

- [x] **You assure that you have tested the modules properly and there are no breaking changes**
- [x] **You adhere to Sazim's [Engineering Principles](https://docs.google.com/document/d/10mowIwsuYMyNkXS7aeL7AJyVNMYVh1vdMf7yn-A6I1k/edit#heading=h.qqetrc8w2lm8)**

## Associated Ticket Link(s)

- https://trello.com/c/g2qYTfYr

## Related Pull Request(s)

- None

## Screenshots / Screen Recordings

2024-10-10 15:17 UTC, nur-zaman-sazim commented
There are duplicate changes in this PR and #18  you might need to change the pointer to the branch

2024-10-11 09:28 UTC, nur-zaman-sazim commented on src/users/users.dtos.ts
> +  role?: number;
ooc: why are we using role as a number ?

2024-10-15 08:45 UTC, nur-zaman-sazim requested changes

2024-10-15 08:45 UTC, nur-zaman-sazim commented on scripts/src/index.ts
> +const sql = postgres("postgresql://postgres:postgres@localhost:5432/project_dev_db");
can we get this from .env ?

2024-10-16 11:08 UTC, tareq-mahmood-sazim commented on scripts/src/index.ts
> +const sql = postgres("postgresql://postgres:postgres@localhost:5432/project_dev_db");
Yes bhaia this has been fixed

2024-10-16 11:08 UTC, tareq-mahmood-sazim commented on src/users/users.dtos.ts
> +  role?: number;
To handle permission levels, the higher the number is, the lower the permissions will be.

2024-10-27 17:08 UTC, nur-zaman-sazim approved these changes

2024-10-28 09:27 UTC, merged