St-10: Create user registration
tareq-mahmood-sazim/superteacher-backend pull request #18
Opened 2024-10-08 10:24 UTC by tareq-mahmood-sazim

## Description of Change

- Users can register based upon profile
- Two types of user, Student, Teacher
- teachers require unique code to register successfully
- validation pipelines were added in the template initially
- dependabot removed

## Please list which modules are affected by your changes

users/**.ts, common/entity/otp.entity
scripts/src/index.ts, scripts/dist/index.js, srcipts.tsconfig.json

---

- [x] **You assure that you have tested the modules properly and there are no breaking changes**
- [x] **You adhere to Sazim's [Engineering Principles](https://docs.google.com/document/d/10mowIwsuYMyNkXS7aeL7AJyVNMYVh1vdMf7yn-A6I1k/edit#heading=h.qqetrc8w2lm8)**

## Associated Ticket Link(s)

- https://trello.com/c/UbaTFp0c

## Related Pull Request(s)

- none

## Screenshots / Screen Recordings

2024-10-10 15:14 UTC, nur-zaman-sazim requested changes

2024-10-10 23:22 UTC, tareq-mahmood-sazim commented on scripts/dist/index.js
bhaia the script was transpiled manually, thus, by removing this file, a unique code cannot be generated.

2024-10-11 09:25 UTC, nur-zaman-sazim commented on scripts/dist/index.js
Can we add a script in the package.json to transpile the code instead of pre - transpiling it ?

2024-10-14 07:29 UTC, tareq-mahmood-sazim commented on scripts/dist/index.js
yes bhaia this can be done, approaching this.

2024-10-16 10:13 UTC, nur-zaman-sazim commented on src/users/users.repository.ts
can we do something like . Would make the code more readable and concise 

```
    const user = new User(email, password);
    const userProfile = new UserProfile(firstName, lastName);

    wrap(userProfile).assign({
      user,
      role,
      gender,
      majorSubject: majorSubject ?? "",
      educationLevel: educationLevel ?? null,
      medium: medium ?? null,
      highestEducationLevel: highestEducationLevel ?? null,
      subjectsToTeach: subjectsToTeach ?? null,
      classLevel: classLevel ?? null,
      degree: degree ?? null,
      semesterOrYear: semesterOrYear ?? null,
    });
```

2024-10-16 11:11 UTC, tareq-mahmood-sazim commented on src/users/users.repository.ts
I was not introduced with something like this, but this actually makes the code more readable, yes bhaia, attempting this approach now.

2024-10-27 17:09 UTC, nur-zaman-sazim approved these changes

2024-10-28 09:26 UTC, merged