feat(ST-28): teacher can create classroom
tareq-mahmood-sazim/superteacher-backend pull request #30
Opened 2024-10-21 12:24 UTC by tareq-mahmood-sazim

## Description of Change

- initiated classroom as resource
- create endpoints to receive the classroom creation payload
- provide validation for the payload
- fetching teacher profile by the JWT token from bearer token passed on the request payload
- creating classroom by adding the teacher ID as owner of the classroom

## Please list which modules are affected by your changes

@/src/classrooms/**.ts

---

- [x] **You assure that you have tested the modules properly and there are no breaking changes**
- [x] **You adhere to Sazim's [Engineering Principles](https://docs.google.com/document/d/10mowIwsuYMyNkXS7aeL7AJyVNMYVh1vdMf7yn-A6I1k/edit#heading=h.qqetrc8w2lm8)**

## Associated Ticket Link(s)

- https://trello.com/c/iiLEBcph

## Related Pull Request(s)

-

## Screenshots / Screen Recordings

2024-11-05 00:06 UTC, nur-zaman-sazim requested changes

2024-11-05 00:06 UTC, nur-zaman-sazim commented on src/classrooms/classrooms.repository.ts
> +    timeAsDate.setHours(Number(hours), Number(minutes), 0, 0);
please use dayjs for date related calculations

2024-11-05 12:27 UTC, tareq-mahmood-sazim commented on package.json
> +    "dev:prepare": "yarn format && yarn lint && yarn build",
I run this command just before pushing codes to github, this command formats the code using prettier, runs prettier to show if there are type issues, runs build command to ensure there are no build errors.

This command basically simulates the configured github action for this project in the localhost.

2024-11-08 04:31 UTC, nur-zaman-sazim approved these changes

2024-11-10 10:52 UTC, merged