feat(ST-44): searching, adding, removing participants on classroom added
tareq-mahmood-sazim/superteacher-backend pull request #38
Opened 2024-10-31 11:28 UTC by tareq-mahmood-sazim

## Description of Change

- Endpoint created for searching students by name and id
- Endpoint created for getting teachers by ID
- Endpoint created for adding students into classroom
- Endpoint created for removing students from classroom
- Authguard provided over adding and removing students to ensure role permissions.

## Please list which modules are affected by your changes

src/classrooms/*, src/users/*
---

- [x] **You assure that you have tested the modules properly and there are no breaking changes**
- [x] **You adhere to Sazim's [Engineering Principles](https://docs.google.com/document/d/10mowIwsuYMyNkXS7aeL7AJyVNMYVh1vdMf7yn-A6I1k/edit#heading=h.qqetrc8w2lm8)**

## Associated Ticket Link(s)

- https://trello.com/c/5nmO0Q4u

## Related Pull Request(s)

-

## Screenshots / Screen Recordings

2024-11-05 00:43 UTC, nur-zaman-sazim requested changes

2024-11-05 00:43 UTC, nur-zaman-sazim commented on src/classrooms/classrooms.controller.ts
> +  RemoveParticipant(
nit: please use a small r in removeParticipant

2024-11-05 00:43 UTC, nur-zaman-sazim commented on src/users/users.controller.ts
Let's combine our /student/search/name/:param and /student/search/email/:param routes into a single /student/search endpoint with a query parameter (e.g., ?name=value or ?email=value).

We can even drop the /search/ part as well

2024-11-05 00:43 UTC, nur-zaman-sazim commented on src/users/users.controller.ts
> +    const student = await this.usersService.getStudentById(parseInt(param.id));
what if the ID can't be parsed?
can we handle this more gracefully?

2024-11-05 00:43 UTC, nur-zaman-sazim commented on src/users/users.module.ts
> +  providers: [UsersService, UsersSerializer, UniquecodeRepository, UsersProfileSerializer],
ooc: why do we have two different UserSerializer and userProfileSerializer

2024-11-10 11:52 UTC, tareq-mahmood-sazim commented on src/users/users.controller.ts
I felt this nest was necessary as I am getting the students by id and in some cases email or name as regex. keeping single endpoint would complicate that single endpoint bhaia.

2024-11-12 11:47 UTC, tareq-mahmood-sazim commented on src/users/users.module.ts
> +  providers: [UsersService, UsersSerializer, UniquecodeRepository, UsersProfileSerializer],
UserSerializer removes secrets from User entity, UserProfile removes secrets from User-Profile Entity

2024-11-17 08:12 UTC, nur-zaman-sazim approved these changes

2024-11-17 09:03 UTC, merged